// <auto-generated />
using System;
using CapsulaDoTempo.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapsulaDoTempo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250626032832_Add email to model")]
    partial class Addemailtomodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("CapsulaDoTempo.Entities.CapsulaModel", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateToSend")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathImage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.ToTable("Capsula");
                });

            modelBuilder.Entity("CapsulaDoTempo.Entities.CapsulaModel", b =>
                {
                    b.OwnsOne("CapsulaDoTempo.Entities.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CapsulaModelUuid")
                                .HasColumnType("TEXT");

                            b1.HasKey("CapsulaModelUuid");

                            b1.ToTable("Capsula");

                            b1.WithOwner()
                                .HasForeignKey("CapsulaModelUuid");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
